### ISSUE TITLE
Custom Key Layout

### ISSUE THREAD

**Issue by Vince14Genius** [Vince14Genius/IPA-Keyboard-iOS#18]
### todo
- [ ] refactor the type-based layouting into `Codable` structs
- [ ] import & export from JSON files
- [ ] customized key layout editor
- [ ] custom layouts will only have 4 rows available for now, so pad extra nils for iPad

### IAP pricing tiers
plus = additional fee from previous tier

- free - 2 slots, 1 section
- +$2.99 - 5 slots, 1 section
- +$5.99 - 20 slots, 1 section
- +$9.99 - 50 slots per section, 5 sections max

### things to consider
- [ ] allow sharing of the generated JSON files (input sanitation needed), limit import capacity by paid status, one JSON layout active at a time

**Comment by Hamza1122H** [comment]
H
