### ISSUE TITLE
TODO: Migrate the keyboard extension to SwiftUI

### ISSUE THREAD

**Issue by Vince14Genius** [Vince14Genius/IPA-Keyboard-iOS#7]
The layout will be remade with SwiftUI and wrapped in a UIInputViewController

- [x] top toolbar
- [x] backspace/delete button
- [x] bottom section scrolling row
- [x] content view of key button cells
- [x] key expansion overlay
