### ISSUE TITLE
TODO: add system key press sound effect to other buttons on the keyboard

### ISSUE THREAD

**Issue by Vince14Genius** [Vince14Genius/IPA-Keyboard-iOS#9]
- [x] keys on the top auxiliary row
- [ ] switch keyboards key
- [x] bottom scroll menu (tap)
- [x] delete key

**Comment by Vince14Genius** [comment]
#29
